# Generated by Django 2.2 on 2021-03-09 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0003_auto_20210308_1856'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreate', models.DateField(auto_now_add=True, null=True, verbose_name='Creation date')),
                ('dateUpdate', models.DateField(auto_now=True, null=True, verbose_name='Modification Date')),
                ('referencia', models.CharField(blank=True, help_text='La referncia puede ser un dato de descripcion del porque realiza el pedido', max_length=150, null=True, verbose_name='Referencia de Pedido')),
                ('totalConsultora', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True, verbose_name='Total Consultora')),
                ('totalCatalogo', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True, verbose_name='Total Catalogo')),
                ('userCreate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='userCreateinventario_pedido_related', to=settings.AUTH_USER_MODEL, verbose_name='Creator User')),
                ('userUpdate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='userUpdateinventario_pedido_related', to=settings.AUTH_USER_MODEL, verbose_name='Modifier User')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreate', models.DateField(auto_now_add=True, null=True, verbose_name='Creation date')),
                ('dateUpdate', models.DateField(auto_now=True, null=True, verbose_name='Modification Date')),
                ('pConsultora', models.DecimalField(decimal_places=2, help_text='Precio al que lo compra la consultora', max_digits=12, verbose_name='Precio Consultora')),
                ('pCatalogo', models.DecimalField(decimal_places=2, help_text='Precio al que se vendera el producto', max_digits=12, verbose_name='Precio Catalogo')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Pedido', verbose_name='Pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.Producto', verbose_name='Producto')),
                ('userCreate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='userCreateinventario_detallepedido_related', to=settings.AUTH_USER_MODEL, verbose_name='Creator User')),
                ('userUpdate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='userUpdateinventario_detallepedido_related', to=settings.AUTH_USER_MODEL, verbose_name='Modifier User')),
            ],
            options={
                'verbose_name': 'Detalle de Pedidos',
                'verbose_name_plural': 'Detalles de Pedidos',
            },
        ),
    ]
