# Generated by Django 2.2 on 2021-03-10 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreate', models.DateField(auto_now_add=True, null=True, verbose_name='Creation date')),
                ('dateUpdate', models.DateField(auto_now=True, null=True, verbose_name='Modification Date')),
                ('firts_name', models.CharField(max_length=75, verbose_name='first_name')),
                ('last_name', models.CharField(blank=True, max_length=75, null=True, verbose_name='last_name')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='gender')),
                ('idNumber', models.CharField(blank=True, max_length=75, null=True, verbose_name='Id Number')),
                ('nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('tel', models.CharField(blank=True, max_length=75, null=True, verbose_name='Phone')),
                ('NIT', models.CharField(blank=True, max_length=15, null=True, verbose_name='NIT')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('img', models.ImageField(blank=True, null=True, upload_to='Clientes/%Y/%m/%d', verbose_name='Avatar')),
                ('userCreate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='userCreateclientes_client_related', to=settings.AUTH_USER_MODEL, verbose_name='Creator User')),
                ('userUpdate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='userUpdateclientes_client_related', to=settings.AUTH_USER_MODEL, verbose_name='Modifier User')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Customers',
            },
        ),
    ]
