# Generated by Django 2.2 on 2021-03-04 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreate', models.DateField(auto_now_add=True, null=True, verbose_name='Creation date')),
                ('dateUpdate', models.DateField(auto_now=True, null=True, verbose_name='Modification Date')),
                ('firts_name', models.CharField(max_length=75, verbose_name='first_name')),
                ('last_name', models.CharField(blank=True, max_length=75, null=True, verbose_name='last_name')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='gender')),
                ('idNumber', models.CharField(blank=True, max_length=75, null=True, verbose_name='Id Number')),
                ('NIT', models.CharField(max_length=15, verbose_name='NIT')),
                ('img', models.ImageField(blank=True, null=True, upload_to='Users/%Y/%m/%d', verbose_name='Avatar')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='PhoneClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreate', models.DateField(auto_now_add=True, null=True, verbose_name='Creation date')),
                ('dateUpdate', models.DateField(auto_now=True, null=True, verbose_name='Modification Date')),
                ('phone_number', models.CharField(help_text='Add a phone number', max_length=15, verbose_name='Phone Number')),
                ('is_favorite', models.BooleanField(help_text='Check only is favorite', verbose_name='Favorite')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Client', verbose_name='Client Phone Number')),
            ],
            options={
                'verbose_name': 'Phone',
                'verbose_name_plural': 'Phones',
            },
        ),
    ]
