# Generated by Django 2.2 on 2021-03-04 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneclient',
            name='userCreate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='userCreateclientes_phoneclient_related', to=settings.AUTH_USER_MODEL, verbose_name='Creator User'),
        ),
        migrations.AddField(
            model_name='phoneclient',
            name='userUpdate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='userUpdateclientes_phoneclient_related', to=settings.AUTH_USER_MODEL, verbose_name='Modifier User'),
        ),
        migrations.AddField(
            model_name='client',
            name='userCreate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='userCreateclientes_client_related', to=settings.AUTH_USER_MODEL, verbose_name='Creator User'),
        ),
        migrations.AddField(
            model_name='client',
            name='userUpdate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='userUpdateclientes_client_related', to=settings.AUTH_USER_MODEL, verbose_name='Modifier User'),
        ),
    ]
