# Generated by Django 2.2 on 2021-03-05 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_auto_20210304_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
