# Generated by Django 2.2 on 2021-03-05 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_client_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneclient',
            name='is_favorite',
            field=models.BooleanField(default=True, help_text='Check only is favorite', verbose_name='Favorite'),
        ),
    ]
