# Generated by Django 2.2 on 2021-03-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_auto_20210304_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='Clientes/%Y/%m/%d', verbose_name='Avatar'),
        ),
    ]
