# Generated by Django 2.2 on 2021-03-03 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, verbose_name='_Phone_Number')),
                ('is_favorite', models.BooleanField(verbose_name='_Favorite')),
            ],
        ),
    ]
