# Generated by Django 2.2 on 2021-03-03 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='is_favorite',
            field=models.BooleanField(verbose_name='Favorite'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='Phone Number'),
        ),
    ]
