# Generated by Django 2.2 on 2021-03-03 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210302_2347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phone',
            options={'verbose_name': 'Phone', 'verbose_name_plural': 'Phones'},
        ),
        migrations.AlterField(
            model_name='phone',
            name='is_favorite',
            field=models.BooleanField(help_text='Check only is favorite', verbose_name='Favorite'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_number',
            field=models.CharField(help_text='Add a phone number', max_length=15, verbose_name='Phone Number'),
        ),
    ]
